In [1]:
# import pip

# def install(package):
#     if hasattr(pip, 'main'):
#         pip.main(['install', package])
#     else:
#         pip._internal.main(['install', package])

# # Example
# install('')

In [2]:
import pandas as pd
import matplotlib as plt
import numpy as np

In [3]:
# pd.np.set_printoptions(suppress=True)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
data = pd.read_csv('jan20_01-21_000000-235959.csv')

/usr/local/Cellar/jupyterlab/3.0.12/libexec/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (29) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [32]:
data

,rt_created_at,rt_author_id,rt_lang,rt_text,rt_id,rt_ref_tweet_id,rt_ref_tweet_type,rt_rt_count,rt_rp_count,rt_lk_count,rt_qt_count,t_created_at,t_id,t_author_id,t_text,t_rt_count,t_rp_count,t_lk_count,t_qt_count,id,name,verified,username,created_at,followers_count,following_count,tweet_count,listed_count,location,withheld
0,2020-01-01 11:59:57+00:00,28967452,en,"RT @vmyths: FYI, I'm going to drive home on Fl...",1212342694908964864,1.212201e+18,['retweeted'],653,0,0,0,2020-01-01 02:38:32+00:00,1.212201e+18,2.802593e+07,"FYI, I'm going to drive home on Florida's Turn...",653.0,60.0,1973.0,96.0,28967452,mulletti,False,mulletti,2009-04-05 10:02:13+00:00,129,178,7177,12,NaN,NaN
1,2020-01-01 11:59:44+00:00,57283792,in,@ardnif Dindin kebanjiran?? Staysafe yaaa Din 😘,1212342641804754944,1.212342e+18,['replied_to'],0,1,0,0,2020-01-01 11:58:42+00:00,1.212342e+18,1.665058e+08,isi powerbank cuma pas mau ngonser atau pergi ...,0.0,1.0,0.0,0.0,57283792,its me,False,seffiii,2009-07-16 08:51:10+00:00,594,769,29980,0,NaN,NaN
2,2020-01-01 11:59:44+00:00,211845768,en,Except you can’t sue vaccine manufacturers htt...,1212342640584380417,1.212236e+18,['quoted'],0,0,1,0,2020-01-01 04:56:57+00:00,1.212236e+18,2.261946e+08,Just heard a medicine commercial say “If you h...,52.0,17.0,255.0,3.0,211845768,suededsusan,False,suededsusan,2010-11-04 12:35:42+00:00,900,520,16330,4,NaN,NaN
3,2020-01-01 11:59:01+00:00,119321075,en,RT @AmyMek: Happy New Year from Sharia Sweden....,1212342462229954560,1.212264e+18,['retweeted'],1912,0,0,0,2020-01-01 06:46:05+00:00,1.212264e+18,9.541244e+08,Happy New Year from Sharia Sweden...\n\n'Gang ...,1912.0,197.0,2467.0,168.0,119321075,Sares,False,fheras,2010-03-03 08:41:25+00:00,2858,5002,91948,25,NaN,NaN
4,2020-01-01 11:58:58+00:00,1391090496,en,RT @AmyMek: Happy New Year from Sharia Sweden....,1212342448057401344,1.212264e+18,['retweeted'],1912,0,0,0,2020-01-01 06:46:05+00:00,1.212264e+18,9.541244e+08,Happy New Year from Sharia Sweden...\n\n'Gang ...,1912.0,197.0,2467.0,168.0,1391090496,robert murphy,False,TheMetroMutt,2013-04-30 04:04:04+00:00,412,911,30777,1,"Quincy, MA",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
782916,2020-01-08 00:00:07+00:00,1148252342048952322,en,RT @AesopsFableFly: ——— BTS LOCKDOWN ———\n\nwh...,1214698259702259715,1.214664e+18,['retweeted'],14892,0,0,0,2020-01-07 21:42:20+00:00,1.214664e+18,9.070342e+17,——— BTS LOCKDOWN ———\n\nwhat is a bts lockdown...,14892.0,116.0,27874.0,281.0,1148252342048952322,BELBEL¹¹⁷ | Blue & Grey ᴮᴱ,False,bangtanniexoxo,2019-07-08 15:27:46+00:00,218,743,18674,0,Argentina,NaN
782917,2020-01-08 00:00:05+00:00,23948496,en,A resident of West Courthouse Road found Coope...,1214698249765961729,NaN,[],0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23948496,8News WRIC Richmond,True,8NEWS,2009-03-12 13:45:41+00:00,102114,1591,180062,1056,"Richmond, Virginia",NaN
782918,2020-01-08 00:00:04+00:00,306412670,en,"#Zambia has 17 million people, a stroke epidem...",1214698246884474880,NaN,[],0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,306412670,Lindsay K. Saunders (she/her) 🇺🇸🇿🇲,False,LindsayKelleyS,2011-05-27 20:53:27+00:00,1823,2732,36784,173,"Raleigh, NC",NaN
782919,2020-01-08 00:00:02+00:00,632909553,en,RT @AesopsFableFly: ——— BTS LOCKDOWN ———\n\nwh...,1214698238541996035,1.214664e+18,['retweeted'],14892,0,0,0,2020-01-07 21:42:20+00:00,1.214664e+18,9.070342e+17,——— BTS LOCKDOWN ———\n\nwhat is a bts lockdown...,14892.0,116.0,27874.0,281.0,632909553,ᴮᴱLintu7676⁷ 🐋 ♡ ²⁰¹³ ♡ BTS fan,False,Lintu7676,2012-07-11 11:50:49+00:00,292,524,11819,5,Belgique,NaN
782920,2020-01-08 00:00:00+00:00,352051593,ja,四種混合（百日せき、ジフテリア、破傷風、ポリオ）予防接種の接種対象年齢は、生後３か月から90...,1214698230497169408,NaN,[],0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,352051593,久慈市 保健推進課,False,kujicity_hoken,2011-08-10 02:35:23+00:00,264,0,12794,20,岩手県久慈市,NaN

In [6]:
df_rt = data[['rt_author_id', 't_author_id', 'rt_text', 't_text']]

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer(analyzer='word',token_pattern=r'[\w\@\#]+')

In [9]:
vec = cv.fit_transform(df_rt.rt_text.dropna().to_numpy())

In [10]:
# with open('cv.txt', 'w') as f:
#     f.write("\n".join(cv.get_feature_names()))

In [11]:
# vec.sum(axis=0) ## get each column sum

In [12]:
# np.array([[1,2],[1,2]]).sum(axis=1) # axis=1 ## check

In [13]:
labels = cv.get_feature_names() ## get all features/lables from the df

In [14]:
## get all mentions/hashtags and their indiceis
mentions = []
mention_indicies = []
hashtags = []
hashtag_indicies = []

In [15]:
## enumerate through them
for i, v in enumerate(labels):
    if v.startswith('@'):
        mentions.append(v)
        mention_indicies.append(i)
    elif v.startswith('#'):
        hashtags.append(v)
        hashtag_indicies.append(i)

In [16]:
# len(mentions)

In [17]:
# np.array(mentions)[[0,1]]

In [18]:
## convert to np array to avoid sparse matrix
mentions = np.array(mentions)
mention_indicies = np.array(mention_indicies)
hashtags = np.array(hashtags)
hashtag_indicies = np.array(hashtag_indicies)

In [19]:
## get the columns vector for mentions and hashtags
mention_vec = vec[:,mention_indicies]
hashtag_vec = vec[:,hashtag_indicies]

In [20]:
## rank the indicies from all counts to get top mentions/tags
mentions_count = np.array(mention_vec.sum(axis=0)).flatten() # Convert flatten(): matrix to 1darray
mentions_rank_indicies = mentions_count.argsort()[::-1] # argsort returns the index o the value

hashtags_count = np.array(hashtag_vec.sum(axis=0)).flatten()
hashtags_rank_indicies = hashtags_count.argsort()[::-1]

In [21]:
## now get mention/hashtag ranked accordingly
mentions_ranked = mentions[mentions_rank_indicies]
hashtags_ranked = hashtags[hashtags_rank_indicies]

In [22]:
# top10mentions = mentions_ranked.tolist()[::-1][:10]
# top10hashtags = hashtags_ranked.tolist()[::-1][:10]

In [23]:
top10mentions_vec = vec[:,mention_indicies[mentions_rank_indicies[:10]]].toarray()
top10hashtags_vec = vec[:,hashtag_indicies[hashtags_rank_indicies[:10]]].toarray()

In [24]:
mentions_ranked.tolist()[::1][:20]

['@who',
 '@teeratr',
 '@vorachatmd',
 '@aesopsfablefly',
 '@cnn',
 '@kieru_chan',
 '@zulmacucunuba',
 '@spectatorindex',
 '@cbcalerts',
 '@nytimes',
 '@declanoscanlon',
 '@peterhotez',
 '@amitshah',
 '@realdonaldtrump',
 '@cdcgov',
 '@drtedros',
 '@cnnee',
 '@mdo526',
 '@joebiden',
 '@highwiretalk']

In [25]:
hashtags_ranked.tolist()[::1][:20]

['#coronavirus',
 '#china',
 '#wuhan',
 '#staysafe',
 '#vaccine',
 '#breaking',
 '#wuhanpneumonia',
 '#flu',
 '#vaccinesafety',
 '#pneumonia',
 '#beijing',
 '#shenzhen',
 '#virus',
 '#kashmir',
 '#lockdown',
 '#últimahora',
 '#health',
 '#update',
 '#vaccines',
 '#']

In [26]:
df_rt['mention_WHO'] = top10mentions_vec[:,0]
df_rt['tag_CORONAVIRUS'] = top10hashtags_vec[:,0]

<ipython-input-26-b8ec78a14ea8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rt['mention_WHO'] = top10mentions_vec[:,0]
<ipython-input-26-b8ec78a14ea8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rt['tag_CORONAVIRUS'] = top10hashtags_vec[:,0]

In [27]:
df_rt[df_rt.mention_WHO>0]

,rt_author_id,t_author_id,rt_text,t_text,mention_WHO,tag_CORONAVIRUS
2111,488292054,1.954403e+09,@thecableng @WHO @nighealthwatch @DrOlufunmila...,TheCable names Stella Adadevoh as ‘Nigerian of...,1,0
3280,1105064943794245632,1.415915e+07,@UN @WHO Yup but Kashmir issues where are you?...,"As you start a new year, check out these 12 ti...",1,0
4881,2476070574,1.174222e+18,RT @TBG9270584: Maine Puts Vaccine Mandates to...,Maine Puts Vaccine Mandates to a Popular Vote ...,1,0
5096,426776226,1.449983e+07,RT @WHO: It's World Immunization Week! \n\nVac...,It's World Immunization Week! \n\nVaccine-prev...,1,0
5490,1183658840077680640,1.174222e+18,RT @TBG9270584: Maine Puts Vaccine Mandates to...,Maine Puts Vaccine Mandates to a Popular Vote ...,1,0
...,...,...,...,...,...,...
772199,3293886549,NaN,The death toll from a measles epidemic in the ...,NaN,1,0
772214,7587032,NaN,The death toll from a measles epidemic in the ...,NaN,1,0
774033,4784948594,2.919391e+09,@cmohry @PMOIndia @narendramodi @mlkhattar @WH...,@dpkchnindia Please share your contact number ...,1,0
775518,1173286656,7.039767e+17,RT @scleroplex: One more detailed report from ...,One more detailed report from @HelenBranswell ...,1,0
775866,703976714704007169,NaN,One more detailed report from @HelenBranswell ...,NaN,1,0

In [28]:
df_rt[df_rt.tag_CORONAVIRUS>0]

,rt_author_id,t_author_id,rt_text,t_text,mention_WHO,tag_CORONAVIRUS
328,364476368,2.992740e+08,"Simply...si no és #coronavirus, NO hi ha #SARS...",@HelenBranswell @ProMED_mail Etiology still un...,0,1
3730,168425731,NaN,Update of a cluster of #Patients infected with...,NaN,0,1
15033,968761746,3.644764e+08,RT @XavierAbadMdG: Simply...si no és #coronavi...,"Simply...si no és #coronavirus, NO hi ha #SARS...",0,1
21707,3420619451,7.268010e+17,RT @Azeria64Azeria: Infections à #MERS-CoV au ...,Infections à #MERS-CoV au Qatar ...,0,1
22116,726801029963108352,7.843517e+17,Infections à #MERS-CoV au Qatar ...,Last week Qatar reported three cases of #MERS ...,0,1
...,...,...,...,...,...,...
771104,472783323,4.727833e+08,"‘Interferon, Ribavirin and protease inhibitors...","According to a news report by @icablenews, Pro...",0,1
771233,472783323,NaN,"According to a news report by @icablenews, Pro...",NaN,0,1
777543,42317370,3.701120e+07,RT @ProMED_mail: It’s not known whether a #SAR...,It’s not known whether a #SARS-like “#coronavi...,0,1
778139,59955964,3.701120e+07,RT @ProMED_mail: It’s not known whether a #SAR...,It’s not known whether a #SARS-like “#coronavi...,0,1
782417,2713078423,3.701120e+07,RT @ProMED_mail: It’s not known whether a #SAR...,It’s not known whether a #SARS-like “#coronavi...,0,1

In [33]:
df_rt.to_csv('df_rt_top_mntns_and_hashtags_jan_1-21.csv', index=False, sep=',')

In [40]:
mention_indicies[mentions_rank_indicies].shape

(100741,)

In [37]:
vec[:,mention_indicies[mentions_rank_indicies[:10]]].toarray().shape

(782921, 10)

In [38]:
pd.read_csv('df_rt_top_mntns_and_hashtags_jan_1-21.csv')

/usr/local/Cellar/jupyterlab/3.0.12/libexec/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (0,1,2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,rt_author_id,t_author_id,rt_text,t_text,mention_WHO,tag_CORONAVIRUS
0,28967452,28025927.0,"RT @vmyths: FYI, I'm going to drive home on Fl...","FYI, I'm going to drive home on Florida's Turn...",0.0,0.0
1,57283792,166505824.0,@ardnif Dindin kebanjiran?? Staysafe yaaa Din 😘,isi powerbank cuma pas mau ngonser atau pergi ...,0.0,0.0
2,211845768,226194552.0,Except you can’t sue vaccine manufacturers htt...,Just heard a medicine commercial say “If you h...,0.0,0.0
3,119321075,954124423.0,RT @AmyMek: Happy New Year from Sharia Sweden....,Happy New Year from Sharia Sweden...\n\n'Gang ...,0.0,0.0
4,1391090496,954124423.0,RT @AmyMek: Happy New Year from Sharia Sweden....,Happy New Year from Sharia Sweden...\n\n'Gang ...,0.0,0.0
...,...,...,...,...,...,...
2266507,1148252342048952322,907034217636343808.0,RT @AesopsFableFly: ——— BTS LOCKDOWN ———\n\nwh...,——— BTS LOCKDOWN ———\n\nwhat is a bts lockdown...,0.0,0.0
2266508,23948496,NaN,A resident of West Courthouse Road found Coope...,NaN,0.0,0.0
2266509,306412670,NaN,"#Zambia has 17 million people, a stroke epidem...",NaN,0.0,0.0
2266510,632909553,907034217636343808.0,RT @AesopsFableFly: ——— BTS LOCKDOWN ———\n\nwh...,——— BTS LOCKDOWN ———\n\nwhat is a bts lockdown...,0.0,0.0
2266511,352051593,NaN,四種混合（百日せき、ジフテリア、破傷風、ポリオ）予防接種の接種対象年齢は、生後３か月から90...,NaN,0.0,0.0